apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    tier: nginx
spec:
  selector:
    matchLabels:
      tier: nginx
  replicas: 3
  template:
    metadata:
      name: httpd-frontend
      labels:
        tier: nginx       
    spec:
      containers:
        - name: nginx-app
          image: nginx:1.19