apiVersion: v1
kind: Service
metadata:
  name: potgres
  labels:
    app: voting-app
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgresql
    app: voting-app