apiVersion: v1
kind: Pod
metadata:
  name: postgresql
  labels:
    name: postgresql
    app: voting-app
spec:
  containers:
    - name: postgresql-db
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
