apiVersion: v1
kind: Pod
metadata:
  name: result-app
  labels:
    name: result-app
    app: voting-app
spec:
  containers:
    - name: frontend-result-app
      image: kodekloud/examplevotingapp_result:v1
      ports:
        - containerPort: 80