apiVersion: v1
kind: Service
metadata:
  name: voting
  labels:
    name: voting
    app: voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    name: voting
    app: voting-app
