apiVersion: v1
kind: Pod
metadata:
  name: voting
  labels:
    name: voting
    app: voting-app
spec:
  containers:
    - name: fontend-voting-app
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80
    